name: 'terraform-workflow'
on:
  push:
    branches:
      - 'release/**'
  pull_request:
  
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Building Docker Image'
      run: docker build . --file Dockerfile --build-arg RUNNER_VERSION=2.303.0 --tag github-runner --no-cache --progress=plain
#     env:
#       GH_TOKEN: ${{ secrets.GH_TOKEN }} 
