name: 'terraform-workflow'
on:
  push:
    branches:
      - 'release/**'
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} 
